### ISSUE TITLE
SyntaxError crash

### ISSUE THREAD

**Issue by Chromelon** [MrRio/vtop#121]
Hi, I'm getting a SyntaxError crash when running vtop, the error message is as follows:

```
evalmachine.<anonymous>:2
vtop@0.5.7 | MIT | deps: 10 | versions: 47
^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInNewContext (vm.js:291:10)
    at safeEval (/usr/lib/node_modules/vtop/node_modules/safe-eval/index.js:13:6)
    at /usr/lib/node_modules/vtop/upgrade.js:25:24
    at ChildProcess.exithandler (child_process.js:273:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:947:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
```

**Comment by williamboman** [comment]
This is caused by breaking changes in `npm@6` CLI API.

**Comment by alichtman** [comment]
Last night I was able to reproduce this with the same setup as @vinkla, but I upgraded both `Node` and `npm`, and now everything works.

```
macOS 10.13.4
node v10.1.0
npm v6.1.0
```

**Comment by tvanantwerp** [comment]
Getting the same error message on a new iMac. Worked fine yesterday when I installed it, but not today.

```
evalmachine.<anonymous>:2
vtop@0.5.7 | MIT | deps: 10 | versions: 47
^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInNewContext (vm.js:291:10)
    at safeEval (/Users/me/.config/yarn/global/node_modules/safe-eval/index.js:13:6)
    at /Users/me/.config/yarn/global/node_modules/vtop/upgrade.js:25:24
    at ChildProcess.exithandler (child_process.js:282:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
```

System details:
```
macOS 10.13.4
node 10.3.0
yarn 1.7.0
```

**Comment by williamboman** [comment]
> Last night I was able to reproduce this with the same setup as @vinkla, but I upgraded both Node and npm, and now everything works.

Did you happen to be offline when it worked? Random guess: the child process didn't exit because `npm info` never resolved due to being offline, meaning the erroneous code never executed.

**Comment by tvanantwerp** [comment]
Nope, online the entire time. Plugged in to the office network.

**Comment by williamboman** [comment]
Are you behind a corporate web proxy then? It is not uncommon that corp proxies block npm traffic.

**Comment by tvanantwerp** [comment]
Nope, no proxies set up. Never had any issues before with accessing npm or
anything else. It's a small company and I'm the IT manager here, and I try
to keep things simple for myself because I don't have anyone else to help
if things break..

**Comment by williamboman** [comment]
🤔..

Anyways, for now I've published `vtop-node10` which includes #123 and thus support for `node@10/npm@6`. To install:

```sh
$ npm uninstall -g vtop
$ npm install -g vtop-node10
$ vtop
```

**Comment by tvanantwerp** [comment]
That worked, thanks!

**Comment by siddharthkul** [comment]
@williamboman you sir are a genius!

**Comment by MrRio** [comment]
This is now fixed in v0.6.0. Thanks for your patience! :)

**Comment by jsatk** [comment]
![screen shot 2018-06-25 at 9 34 16 am](https://user-images.githubusercontent.com/1005550/41863216-f659f1f6-785a-11e8-9e37-a536e2e62a1d.png)

Still failing for me.

**Comment by smukkejohan** [comment]
I'm having the same issue in 0.6.1

**Comment by Blake-LeBlanc** [comment]
> I'm having the same issue in 0.6.1

Same. I'm going to try the above vtop-node10 version, will report back on how that goes.

UPDATE: installing vtop-node10 seems to have FIXED the issues on my end
